projects:
  avocado:
    schemaPath: amplify/backend/api/avocado/build/schema.graphql
    includes:
      - graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
